name: dyna-blaster # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Version of Bomberman
description: |
  Version of Bomberman

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  dyna-blaster_icon.png
title: Dyna Blaster (DOS)

apps:
  dyna-blaster:
    command: dosbox -exit DYNA.EXE
parts:
  dyna-blaster:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [dosbox]
    stage-packages: [dosbox]
    organize:
      dyna-blaster: build/
      dyna-blaster.1: man/man1/

architectures:
  - build-on: amd64
  - build-on: i386

